baseurl = "https://liuyanguu.github.io/"
publishDir  = "D:/liuyanguu/liuyanguu.github.io/"
languageCode = "en-us"
title = "Welcome to my blog"
theme = "hugo-xmag"
googleAnalytics = "UA-122668586-1"
disqusShortname = "liuyanguu"
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "About Me"
    url = "/about me/"
    weight = 5
    
[params]
    description = "Yang Liu (liuyanguu)'s research blog built by R Blogdown."
    summary_length = 400
    github_edit = "https://github.com/liuyanguu/Blogdown/edit/master/hugo-xmag/content/"
    footer = "@2021 Yang Liu _github.com/liuyanguu_. Powered by Github."

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
    
[params.banner]
    src = "ocean 2.jpg"
    alt = "Text on Image"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true